/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AuthenticationImport } from './routes/authentication'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspaceIdImport } from './routes/workspace.$id'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationRoute = AuthenticationImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspaceIdRoute = WorkspaceIdImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/dashboard': typeof DashboardRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/dashboard': typeof DashboardRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/authentication': typeof AuthenticationRoute
  '/dashboard': typeof DashboardRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authentication' | '/dashboard' | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authentication' | '/dashboard' | '/workspace/$id'
  id: '__root__' | '/' | '/authentication' | '/dashboard' | '/workspace/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationRoute: typeof AuthenticationRoute
  DashboardRoute: typeof DashboardRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationRoute: AuthenticationRoute,
  DashboardRoute: DashboardRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authentication",
        "/dashboard",
        "/workspace/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authentication": {
      "filePath": "authentication.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/workspace/$id": {
      "filePath": "workspace.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
